#!/bin/bash

# Shows selection of available local branches
get_branches="git branch | sort --reverse"

git branch | sort --reverse \
    | fzf +m \
    --style full \
    --reverse \
    --border \
    --border-label " gitui - Branches " \
    --preview-window wrap \
    --preview="git log --color=always --graph --abbrev-commit --decorate --first-parent main..{-1}" \
    --bind "enter:execute-silent(gitui-branch-change {-1})+reload($get_branches)" \
    --bind "delete:execute(gitui-branch-delete normal {-1})+reload($get_branches)" \
    --bind "ctrl-delete:execute(gitui-branch-delete force {-1})+reload($get_branches)"
