#!/bin/bash

# Shows the files in the working directory
get_files="git status --short \
    | awk '/^ M |^MM |^AM |^\?\? / {print}' \
    | cut -c 4- \
    | sed 's/\"//g'"

git status --short \
    | awk '/^ M |^MM |^AM |^\?\? / {print}' \
    | cut -c 4- \
    | sed 's/"//g' \
    | fzf \
    --style full +m \
    --reverse \
    --preview="gitui-preview-working {}" \
    --bind "enter:execute(git add {})+reload($get_files),ctrl-p:execute(git add -p {})+reload($get_files)"
