#!/bin/bash

file_state=$(git status --short "$1" | cut -c 1-3)

is_mod=$(echo "$file_state" | awk '/ M |MM |AM | D / {print "true"}')
is_new=$(echo "$file_state" | awk '/\?\? / {print "true"}')

#partially added missing

echo "[WORKING]"
echo ""

if [[ $is_mod == "true" ]]; then
    git diff "$1"
fi

if [[ $is_new == "true" ]]; then
    less "$1"
fi
