#!/bin/bash

file_state=$(git status --short "$1" | cut -c 1-3)

is_mod=$(echo "$file_state" | awk '/M  | M |MM |AM |A  / {print "true"}')
is_deleted=$(echo "$file_state" | awk '/D  / {print "true"}')

#partially added missing

if [[ $is_mod == "true" ]]; then
    git diff --color=always --staged "$1"
fi

if [[ $is_deleted == "true" ]]; then
    git diff --color=always --cached -- "$1"
fi
