#!/bin/zsh

# TODO: Make this a proper bash script

if [ -n "$1" ]
then
    read -r -k 1 "response?Do you really want to discard the changes in '$1'? "
    echo    # (optional) move to a new line

    if [[ "$response" =~ ^[Yy]$ ]]
    then
        file_status=$(git status --short "$1")
        is_mod=$(echo "$file_status" | awk '/^?M / {print "true"}')
        is_untracked=$(echo "$file_status" | awk '/^\?\? / {print "true"}')
        is_deleted=$(echo "$file_status" | awk '/^ D / {print "true"}')

        if [[ "$is_mod" == "true" || "$is_deleted" == "true" ]]
        then
            git restore "$1"
        elif [[ "$is_untracked" == "true" ]]
        then
            rm "$1"
        fi
    fi
fi
