#!/bin/bash

repo=$(basename $(pwd))
get_branches="git branch | sort --reverse"
get_remote_branches="git branch -r | sort --reverse"

git branch | sort --reverse \
    | fzf +m \
    --style full \
    --reverse \
    --border \
    --border-label " gitui: $repo - Branches " \
    --preview-window wrap \
    --preview="git log --color=always --graph --abbrev-commit --decorate --first-parent main..{-1}" \
    --bind "enter:execute-silent(gitui-branch-change {-1})+reload($get_branches)" \
    --bind "delete:execute(gitui-branch-delete normal {-1})+reload($get_branches)" \
    --bind "ctrl-delete:execute(gitui-branch-delete force {-1})+reload($get_branches)" \
    --bind "ctrl-r:reload($get_remote_branches)" \
    --bind "ctrl-l:reload($get_branches)" \
    --bind "ctrl-p:execute-silent(git push origin {-1})+refresh-preview" \
    --bind "ctrl-f:execute-silent(git fetch; git pull)"
