#!/bin/bash

# Shows the staged files
get_files="git status --short \
    | awk '/^A  |^AM |^MM |^D  |^M  / {print}' \
    | cut -c 4- \
    | sed 's/\"//g'"

git status --short \
    | awk '/^A  |^AM |^MM |^D  |^M  / {print}' \
    | cut -c 4- \
    | sed 's/"//g' \
    | fzf \
    --style full +m \
    --reverse \
    --border \
    --border-label " gitui - Index " \
    --preview="gitui-preview-index {}" \
    --bind "enter:execute(git restore --staged {})+reload($get_files)" \
    --bind "ctrl-p:execute(git restore --staged -p {})+reload($get_files)"
