#!/bin/bash

repo=$(basename $(pwd))
get_files="git status --short \
    | awk '/^A  |^AM |^MM |^D  |^M  / {print}' \
    | cut -c 4- \
    | sed 's/\"//g'"

git status --short \
    | awk '/^A  |^AM |^MM |^D  |^M  / {print}' \
    | cut -c 4- \
    | sed 's/"//g' \
    | fzf +m \
    --style full \
    --keep-right \
    --reverse \
    --border \
    --border-label " gitui: $repo - Index " \
    --preview-window wrap \
    --preview="gitui-preview-index {}" \
    --bind "enter:execute-silent(git restore --staged {})+reload($get_files)" \
    --bind "ctrl-p:execute(git restore --staged -p {})+reload($get_files)" \
    --bind "ctrl-r:reload($get_files)" \
    --bind "ctrl-w:become(gitui-working)" \
    --bind "tab:become(gitui-commit)" \
    --bind "ctrl-c:execute(git commit -v -q)+reload($get_files)" \
    --bind "ctrl-a:execute(git commit -v -q --amend)+reload($get_files)"
