#!/bin/bash

options="1 Working Directory - gitui-working
2 Index - gitui-index
3 Commit - gitui-commit
4 Branch - gitui-branch
5 History - gitui-history"

selected=$(echo "$options" | fzf \
    --style full \
    --reverse \
    +m \
    --bind "enter:execute({-1})")
