#!/bin/bash

# Shows the files in the working directory
get_files="git status --short \
    | awk '/^ M |^MM |^AM |^ D |^\?\? / {print}' \
    | cut -c 4- \
    | sed 's/\"//g'"

git status --short \
    | awk '/^ M |^MM |^AM |^ D |^\?\? / {print}' \
    | cut -c 4- \
    | sed 's/"//g' \
    | fzf +m \
    --style full \
    --keep-right \
    --reverse \
    --border \
    --border-label " gitui - Working directory " \
    --preview-window wrap \
    --preview="gitui-preview-working {}" \
    --bind "enter:execute-silent(git add {})+reload($get_files)" \
    --bind "ctrl-r:reload($get_files)" \
    --bind "ctrl-i:become(gitui-index)" \
    --bind "ctrl-p:execute(git add -p {})+reload($get_files)" \
    --bind "ctrl-e:execute($EDITOR {})+reload($get_files)" \
    --bind "ctrl-delete:execute(gitui-discard-changes {})+reload($get_files)"
    #Backspace is a problem for the search, you dummy
