#!/bin/bash

file_state=$(git status --short "$1" | cut -c 1-3)

is_mod=$(echo "$file_state" | awk '/M  | M |MM |AM / {print "true"}')
is_deleted=$(echo "$file_state" | awk '/D  / {print "true"}')
is_new=$(echo "$file_state" | awk '/\?\? / {print "true"}') #??

#partially added missing

echo "[INDEX]"
echo ""

if [[ $is_mod == "true" ]]; then
    git diff --staged "$1"
fi

if [[ $is_deleted == "true" ]]; then
    echo "File deleted ..."
fi
