#!/bin/bash

file_state=$(git status --short "$1" | cut -c 1-3)

is_mod_not_staged=$(echo "$file_state" | awk '/ M / {print "true"}')
is_mod_staged=$(echo "$file_state" | awk '/M  / {print "true"}')
is_new=$(echo "$file_state" | awk '/\?\? / {print "true"}')
is_new_added=$(echo "$file_state" | awk '/A  / {print "true"}')

#partially added missing

if [[ $is_mod_not_staged == "true" ]]; then
    echo "[NOT STAGED]"
    echo ""
    git diff "$1"
fi

if [[ $is_mod_staged == "true" ]]; then
    echo "[STAGED]"
    echo ""
    git diff "$1"
fi

if [[ $is_new_added == "true" ]]; then
    echo "[STAGED]"
    echo ""
    git diff --staged "$1"
fi

if [[ $is_new == "true" ]]; then
    echo "[NEW | NOT STAGED]"
    echo ""
    less "$1"
fi
